# Generated by Django 3.2.2 on 2021-05-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_joinusmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinusmodel',
            name='varified',
            field=models.BooleanField(default=False),
        ),
    ]
