# Generated by Django 3.2.2 on 2021-05-15 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_joinusmodel_varified'),
    ]

    operations = [
        migrations.CreateModel(
            name='helpModel',
            fields=[
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=12)),
                ('wpPhone', models.CharField(default='Not available', max_length=12)),
                ('currentAddress', models.CharField(max_length=250)),
                ('permanentAddress', models.CharField(default='Not Available', max_length=100)),
                ('message', models.CharField(default='Description Not Available', max_length=1000)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('isHelpReached', models.BooleanField(default=False)),
            ],
        ),
    ]
