# Generated by Django 3.2.2 on 2021-05-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_helpmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpmodel',
            name='help_type',
            field=models.CharField(default='Not spacified', max_length=50),
        ),
    ]
