# Generated by Django 3.2.2 on 2021-05-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_helpmodel_help_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpmodel',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
